### ISSUE TITLE
flextable dependancy

### ISSUE THREAD

**Issue by davidgohel** [MAnalytics/akmedoids#1]
Hi,

Bu running `revdepcheck::revdep_check()` on flextable I realized your package is suggesting `flextable` but not using it. Would you be ok to drop `flextable` from `Suggests` and from the vignette?

See here : 
https://github.com/MAnalytics/akmedoids/search?q=flextable&unscoped_q=flextable

KR,
David

**Comment by MAnalytics** [comment]
@davidgohel Thanks for the observation. The 'flexable' package has now been dropped from the vignette and the 'description' file.

**Comment by davidgohel** [comment]
@MAnalytics thanks!
